# Generated by Django 5.1.2 on 2025-03-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0005_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='qrbGMfiPNtth5BF96VEl7hYT07HLZeVL', editable=False, max_length=32, unique=True),
        ),
    ]
