# Generated by Django 5.1.2 on 2025-03-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0006_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='nlJlX05GDSHc2374PPzs1mB3gkGIffUl', editable=False, max_length=32, unique=True),
        ),
    ]
